# Generated by Django 6.0.5 on 2026-05-14 13:48

import common.kgs
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(db_index=True, default=common.kgs.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(db_index=True, max_length=20)),
                ('business_name', models.CharField(db_index=True, max_length=100)),
                ('tid', models.CharField(db_index=True, default=common.kgs.generate_uuid, max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(db_index=True, default=common.kgs.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_class', models.CharField(choices=[('transfer', 'transfer'), ('vas', 'vas'), ('cashout', 'cashout'), ('inward', 'inward')], db_index=True, max_length=20)),
                ('transaction_mode', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('successful', 'successful'), ('failed', 'failed')], db_index=True, default='pending', max_length=20)),
                ('narration', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(db_index=True, max_length=10, null=True, unique=True)),
                ('reference', models.CharField(db_index=True, default=common.kgs.generate_uuid, max_length=10, unique=True)),
                ('sender_bank_name', models.CharField(max_length=100, null=True)),
                ('sender_name', models.CharField(max_length=100, null=True)),
                ('receiver_name', models.CharField(max_length=100, null=True)),
                ('sender_account_number', models.CharField(max_length=100, null=True)),
                ('receiver_account_number', models.CharField(max_length=100, null=True)),
                ('old_balance', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transaction.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
