# Generated by Django 6.0.5 on 2026-05-14 15:48

import common.kgs
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='tid',
            field=models.CharField(db_index=True, default=common.kgs.generate_uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
