# Generated by Django 6.0.5 on 2026-05-14 15:53

import common.kgs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_wallet_balance_alter_wallet_tid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(db_index=True, default=common.kgs.generate_uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='session_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
