# Generated by Django 6.0.5 on 2026-05-14 16:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
