FROM python:3.13.3-slim

ENV USER=appuser \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_PROJECT_ENVIRONMENT=/usr/local

RUN apt-get update && apt-get install --no-install-recommends -y curl gcc python3-dev musl-dev  \
    build-essential libpq-dev libmagic1 libffi-dev git netcat-traditional wkhtmltopdf pkg-config libcairo2-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -m -s /bin/bash $USER

COPY --from=ghcr.io/astral-sh/uv:0.5.5 /uv /uvx /bin/

ENV APP_DIR=/home/$USER/src
WORKDIR $APP_DIR

COPY pyproject.toml pyproject.toml
COPY uv.lock uv.lock

RUN --mount=type=cache,target=/home/$USER/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project

COPY app $APP_DIR

RUN --mount=type=cache,target=/home/$USER/.cache/uv \
    uv sync --frozen

ENV PYTHONPATH=$APP_DIR

RUN chown -R "$USER":"$USER" $APP_DIR
USER $USER
RUN mkdir -p /home/$USER/run && chown -R $USER:$USER /home/$USER/run

# Copy the entrypoint script and make it executable
COPY ./docker/celery/entrypoint-celery.sh /entrypoint-celery.sh
#RUN chmod +x  /entrypoint-celery.sh

EXPOSE 5555
# Command for running the app in production (via entrypoint.sh)
ENTRYPOINT ["/entrypoint-celery.sh"]
